[tool.poetry]
name = "repl_python3_flask-hello-world-1"
version = "0.1.0"
description = ""
authors = ["KitaJami <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^1.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
